"""
Download Module - Downloads an image from a specified URL and saves it to a local path with validation.

Auto-generated by ModuleGenerator
Generated at: 2025-12-04T00:14:18.999652
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict
import httpx
from pathlib import Path


@register_module('image.download')
class Download(BaseModule):
    """
    Downloads an image from a specified URL and saves it to a local path with validation.

    Parameters:
        url (str - The URL of the image to download): Parameter description
        save_path (str - The local file path where the image will be saved): Parameter description

    Returns:
        A dictionary with the status of the operation, including success or error details.
    """

    module_name = "Download"
    module_description = "Downloads an image from a specified URL and saves it to a local path with validation."

    def validate_params(self):
        """Validate and extract parameters"""
        if "url" not in self.params:
            raise ValueError("Missing required parameter: url")
        self.url = self.params["url"]
        if "save_path" not in self.params:
            raise ValueError("Missing required parameter: save_path")
        self.save_path = self.params["save_path"]

    async def execute(self) -> Any:
        """
        Execute the module logic

        Returns:
            A dictionary with the status of the operation, including success or error details.
        """
        try:
            # Validate URL format
                if not (self.url.startswith("http://") or self.url.startswith("https://")):
                    return {
                        "status": "error",
                        "message": "Invalid URL: must start with http:// or https://"
                    }

                try:
                    async with httpx.AsyncClient() as client:
                        # First, get headers to check Content-Type and size
                        head_response = await client.head(self.url, timeout=10.0)

                        content_type = head_response.headers.get("content-type", "").lower()
                        if not content_type.startswith("image/"):
                            return {
                                "status": "error",
                                "message": f"Invalid content type: {content_type} (expected image/*)"
                            }

                        content_length = int(head_response.headers.get("content-length", 0))
                        max_size = 50 * 1024 * 1024  # 50 MB
                        if content_length > max_size:
                            return {
                                "status": "error",
                                "message": f"File too large: {content_length} bytes (max: {max_size})"
                            }

                        # Download with streaming
                        async with client.stream("GET", self.url, timeout=30.0) as response:
                            response.raise_for_status()

                            path = Path(self.save_path)
                            path.parent.mkdir(parents=True, exist_ok=True)

                            downloaded_size = 0
                            with open(path, "wb") as f:
                                async for chunk in response.aiter_bytes(chunk_size=8192):
                                    downloaded_size += len(chunk)
                                    if downloaded_size > max_size:
                                        return {
                                            "status": "error",
                                            "message": "File size exceeded limit during download"
                                        }
                                    f.write(chunk)

                            return {
                                "status": "success",
                                "path": str(path),
                                "size": downloaded_size,
                                "url": self.url,
                                "content_type": content_type
                            }

                except httpx.HTTPStatusError as e:
                    return {
                        "status": "error",
                        "message": f"HTTP error: {e.response.status_code}"
                    }
                except httpx.RequestError as e:
                    return {
                        "status": "error",
                        "message": f"Request failed: {str(e)}"
                    }
                except IOError as e:
                    return {
                        "status": "error",
                        "message": f"File I/O error: {str(e)}"
                    }
                except Exception as e:
                    raise RuntimeError(f"Unexpected error: {str(e)}")

        except Exception as e:
            raise RuntimeError(f"{self.module_name} execution failed: {str(e)}")
