"""
Download Module - Downloads an image from a URL and saves it to a specified path.

Auto-generated by ModuleGenerator
Generated at: 2025-12-04T13:44:23.168754
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict
from pathlib import Path
import httpx


@register_module('image.download')
class Download(BaseModule):
    """
    Downloads an image from a URL and saves it to a specified path.

    Parameters:
        url (str): The URL of the image to download
        save_path (str): The file path where the image will be saved

    Returns:
        A dictionary with the status of the download, the path where the image is saved, the size of the image, and the URL of the image.
    """

    module_name = "Download"
    module_description = "Downloads an image from a URL and saves it to a specified path."

    def validate_params(self):
        """Validate and extract parameters."""
        if "url" not in self.params:
            raise ValueError("Missing required parameter: url")
        self.url = self.params["url"]
        if "save_path" not in self.params:
            raise ValueError("Missing required parameter: save_path")
        self.save_path = self.params["save_path"]

    async def execute(self) -> Any:
        """
        Execute the module logic.

        Returns:
            A dictionary with the status of the download, the path where the image is saved, the size of the image, and the URL of the image.
        """
        import httpx
        from pathlib import Path

        async with httpx.AsyncClient() as client:
            try:
                response = await client.get(self.url, timeout=30.0)
                response.raise_for_status()
            except httpx.HTTPStatusError as exc:
                return {
                    "status": "error",
                    "error": f"HTTP error occurred: {exc.response.status_code}"
                }
            except httpx.RequestError as exc:
                return {
                    "status": "error",
                    "error": f"An error occurred while requesting {exc.request.url}: {str(exc)}"
                }

            path = Path(self.save_path)
            path.parent.mkdir(parents=True, exist_ok=True)

            try:
                path.write_bytes(response.content)
            except IOError as exc:
                return {
                    "status": "error",
                    "error": f"Failed to write file: {str(exc)}"
                }

            return {
                "status": "success",
                "path": str(path),
                "size": len(response.content),
                "url": self.url
            }
