"""
SvgConvert Module - Convert SVG file to PNG format

Auto-generated by ModuleGenerator
Generated at: 2025-12-04T14:10:20.138346
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict
from pathlib import Path
import cairosvg


@register_module('image.svg_convert')
class SvgConvert(BaseModule):
    """
    Convert SVG file to PNG format

    Parameters:
        svg_path (str): Path to the SVG file
        png_path (str): Path to save the converted PNG file

    Returns:
        A dictionary indicating success or failure of the conversion process
    """

    module_name = "SvgConvert"
    module_description = "Convert SVG file to PNG format"

    def validate_params(self):
        """Validate and extract parameters."""
        if "svg_path" not in self.params:
            raise ValueError("Missing required parameter: svg_path")
        self.svg_path = self.params["svg_path"]
        if "png_path" not in self.params:
            raise ValueError("Missing required parameter: png_path")
        self.png_path = self.params["png_path"]

    async def execute(self) -> Any:
        """
        Execute the module logic.

        Returns:
            A dictionary indicating success or failure of the conversion process
        """
        import cairosvg
        from pathlib import Path

        svg_path = Path(self.svg_path)
        png_path = Path(self.png_path)

        if not svg_path.exists():
            return {
                "ok": False,
                "output": {},
                "error": {"message": f"SVG file not found: {self.svg_path}"},
                "meta": {}
            }

        try:
            png_path.parent.mkdir(parents=True, exist_ok=True)
            cairosvg.svg2png(url=str(svg_path), write_to=str(png_path))
            return {
                "ok": True,
                "output": {
                    "svg_path": str(svg_path),
                    "png_path": str(png_path)
                },
                "error": None,
                "meta": {}
            }
        except Exception as e:
            return {
                "ok": False,
                "output": {},
                "error": {"message": str(e)},
                "meta": {}
            }
