"""
SvgConvert Module - Convert SVG file to PNG format

Auto-generated by ModuleGenerator
Generated at: 2025-12-03T23:03:42.093818
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict
import cairosvg
from pathlib import Path


@register_module('image.svg_convert')
class SvgConvert(BaseModule):
    """
    Convert SVG file to PNG format

    Parameters:
        svg_path (str - Path to the SVG file): Parameter description
        output_path (str - Path where the converted PNG file will be saved): Parameter description

    Returns:
        A dictionary with status and details of the conversion process
    """

    module_name = "SvgConvert"
    module_description = "Convert SVG file to PNG format"

    def validate_params(self):
        """Validate and extract parameters"""
        if "svg_path" not in self.params:
            raise ValueError("Missing required parameter: svg_path")
        self.svg_path = self.params["svg_path"]
        if "output_path" not in self.params:
            raise ValueError("Missing required parameter: output_path")
        self.output_path = self.params["output_path"]

    async def execute(self) -> Any:
        """
        Execute the module logic

        Returns:
            A dictionary with status and details of the conversion process
        """
        try:
            import cairosvg
            from pathlib import Path

            svg_path = Path(self.svg_path)
            output_path = Path(self.output_path)

            if not svg_path.exists():
                raise FileNotFoundError(f"SVG file not found: {self.svg_path}")

            try:
                output_path.parent.mkdir(parents=True, exist_ok=True)
                cairosvg.svg2png(url=str(svg_path), write_to=str(output_path))
                return {
                    "status": "success",
                    "input_svg": str(svg_path),
                    "output_png": str(output_path),
                    "size": output_path.stat().st_size
                }
            except Exception as e:
                return {
                    "status": "error",
                    "message": str(e)
                }

        except Exception as e:
            raise RuntimeError(f"{self.module_name} execution failed: {str(e)}")
