"""
SvgConvert Module - Convert SVG image to PNG format

Auto-generated by ModuleGenerator
Generated at: 2025-12-03T23:23:18.826496
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict
from cairosvg import svg2png
from pathlib import Path


@register_module('image.svg_convert')
class SvgConvert(BaseModule):
    """
    Convert SVG image to PNG format

    Parameters:
        svg_path (str - Path to the SVG file): Parameter description
        output_path (str - Path where the PNG file will be saved): Parameter description

    Returns:
        Dict with conversion status and output file details
    """

    module_name = "SvgConvert"
    module_description = "Convert SVG image to PNG format"

    def validate_params(self):
        """Validate and extract parameters"""
        if "svg_path" not in self.params:
            raise ValueError("Missing required parameter: svg_path")
        self.svg_path = self.params["svg_path"]
        if "output_path" not in self.params:
            raise ValueError("Missing required parameter: output_path")
        self.output_path = self.params["output_path"]

    async def execute(self) -> Any:
        """
        Execute the module logic

        Returns:
            Dict with conversion status and output file details
        """
        try:
            from cairosvg import svg2png
            from pathlib import Path

            svg_file = Path(self.svg_path)
            output_file = Path(self.output_path)

            if not svg_file.exists():
                raise FileNotFoundError(f"SVG file not found: {self.svg_path}")

            output_file.parent.mkdir(parents=True, exist_ok=True)

            try:
                svg2png(url=str(svg_file), write_to=str(output_file))
            except Exception as e:
                return {
                    "status": "error",
                    "message": str(e)
                }

            return {
                "status": "success",
                "output_path": str(output_file),
                "size": output_file.stat().st_size
            }

        except Exception as e:
            raise RuntimeError(f"{self.module_name} execution failed: {str(e)}")
