"""
Reverse Module - Reverses the input text string

Auto-generated by ModuleGenerator
Generated at: 2025-12-04T01:59:49.775806
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict
from typing import Any, Dict


@register_module('text.reverse')
class Reverse(BaseModule):
    """
    Reverses the input text string

    Parameters:
        text (str - The input text string to reverse): Parameter description

    Returns:
        Dict[str, Any] with keys: ok, output, error, meta
    """

    module_name = "Reverse"
    module_description = "Reverses the input text string"

    def validate_params(self):
        """Validate and extract parameters"""
        if "text" not in self.params:
            raise ValueError("Missing required parameter: text")
        self.text = self.params["text"]

    async def execute(self) -> Any:
        """
        Execute the module logic

        Returns:
            Dict[str, Any] with keys: ok, output, error, meta
        """
        try:
            async def execute(self) -> Any:
                """
                Execute the module logic to reverse a text string.

                Returns:
                    Dict with reversed text string
                """
                try:
                    # Input validation first
                    if not isinstance(self.text, str):
                        return {
                            "ok": False,
                            "output": {},
                            "error": {"message": "Invalid input: text must be a string"},
                            "meta": {}
                        }

                    # Main logic
                    self.reversed_text = self.text[::-1]

                    return {
                        "ok": True,
                        "output": {"reversed_text": self.reversed_text},
                        "error": None,
                        "meta": {}
                    }

                except ValueError as e:
                    return {
                        "ok": False,
                        "output": {},
                        "error": {"message": f"Value error: {str(e)}"},
                        "meta": {}
                    }
                except TypeError as e:
                    return {
                        "ok": False,
                        "output": {},
                        "error": {"message": f"Type error: {str(e)}"},
                        "meta": {}
                    }
                except Exception as e:
                    raise RuntimeError(f"text.reverse execution failed: {str(e)}")

        except Exception as e:
            raise RuntimeError(f"{self.module_name} execution failed: {str(e)}")
