"""
Reverse Module - Reverse a string

Auto-generated by ModuleGenerator
Generated at: 2025-12-01T19:47:36.395961
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict


@register_module('string.reverse')
class Reverse(BaseModule):
    """
    Reverse a string

    Parameters:
        text (string to reverse): Parameter description

    Returns:
        Reversed string
    """

    module_name = "Reverse"
    module_description = "Reverse a string"

    def validate_params(self):
        """Validate and extract parameters"""
        if "text" not in self.params:
            raise ValueError("Missing required parameter: text")
        self.text = self.params["text"]

    async def execute(self) -> Any:
        """
        Execute the module logic

        Returns:
            Reversed string
        """
        try:
            # String operation implementation
            result = str(self.text)[::-1]  # Reverse the string

            return {
                "result": result,
                "original": self.text,
                "length": len(result),
                "status": "success"
            }

        except Exception as e:
            raise RuntimeError(f"{self.module_name} execution failed: {str(e)}")
