"""
Not Module - Auto-generated module: Module not found in registry

Auto-generated by ModuleGenerator
Generated at: 2025-12-03T20:49:04.566228
"""

from src.core.modules.base import BaseModule
from src.core.modules.registry import register_module
from typing import Any, Dict


@register_module('utility.not')
class Not(BaseModule):
    """
    Auto-generated module: Module not found in registry

    Parameters:
        input (any): Parameter description

    Returns:
        Processing result
    """

    module_name = "Not"
    module_description = "Auto-generated module: Module not found in registry"

    def validate_params(self):
        """Validate and extract parameters"""
        if "input" not in self.params:
            raise ValueError("Missing required parameter: input")
        self.input = self.params["input"]

    async def execute(self) -> Any:
        """
        Execute the module logic

        Returns:
            Processing result
        """
        try:
            # Boolean NOT operation
            result = not self.input

            return {
                "ok": True,
                "output": {"result": result},
                "error": None,
                "meta": {}
            }

        except Exception as e:
            return {
                "ok": False,
                "output": {},
                "error": {"message": f"{self.module_name} execution failed: {str(e)}"},
                "meta": {}
            }
