#!/usr/bin/env python3
"""
Setup Cloud Qdrant Configuration

Helps configure Flyto2 to use cloud Qdrant instead of local storage.
This fixes the concurrent access limitation of local Qdrant.
"""

import os
import sys
from pathlib import Path

def create_env_file():
    """Create .env file with Qdrant cloud configuration"""

    print("🌐 Qdrant Cloud Setup")
    print("=" * 60)
    print()
    print("⚠️  IMPORTANT: Local Qdrant is NOT supported!")
    print("   You MUST use Qdrant Cloud or a remote Qdrant server.")
    print()
    print("Choose Qdrant mode:")
    print("  1. Qdrant Cloud (https://cloud.qdrant.io/) [Recommended]")
    print("  2. Custom Remote Qdrant Server")
    print()

    choice = input("Enter choice (1-2): ").strip()

    if choice == "1":
        print("\n📝 Qdrant Cloud Configuration")
        print("-" * 60)
        print("1. Go to https://cloud.qdrant.io/")
        print("2. Create a cluster")
        print("3. Get your cluster URL and API key")
        print()

        url = input("Enter Qdrant Cloud URL (e.g., https://xyz.qdrant.io:6333): ").strip()
        api_key = input("Enter API Key: ").strip()

        if not url or not api_key:
            print("❌ URL and API key are required!")
            return False

        # Validate URL is not localhost
        if "localhost" in url or "127.0.0.1" in url:
            print("❌ Local Qdrant is NOT supported!")
            print("   Please use Qdrant Cloud or a remote server.")
            return False

    elif choice == "2":
        print("\n⚙️ Custom Remote Qdrant Server")
        print("-" * 60)
        print("⚠️  Note: localhost/127.0.0.1 is NOT supported!")
        print()

        url = input("Enter Qdrant URL (e.g., https://your-server:6333): ").strip()
        api_key = input("Enter API Key: ").strip()

        # Validate URL is not localhost
        if "localhost" in url or "127.0.0.1" in url:
            print("❌ Local Qdrant is NOT supported!")
            print("   Please use Qdrant Cloud or a remote server.")
            return False

        if not api_key:
            print("⚠️  Warning: API key is strongly recommended for security.")

    else:
        print("❌ Invalid choice!")
        return False

    # Create .env file
    env_path = Path(__file__).parent.parent / ".env"

    env_content = f"""# Qdrant Configuration
# Generated by setup_cloud_qdrant.py

QDRANT_MODE=cloud
QDRANT_URL={url}
QDRANT_API_KEY={api_key}

# Embedding provider (ollama or openai)
EMBEDDING_PROVIDER=local
"""

    with open(env_path, 'w') as f:
        f.write(env_content)

    print()
    print("✅ .env file created successfully!")
    print(f"   Location: {env_path}")
    print()

    return True


def update_doc_ingestion():
    """Update doc_ingestion.py to read from .env"""

    print("📝 Updating doc_ingestion.py...")

    doc_ingestion_path = Path(__file__).parent.parent / "src/core/knowledge/doc_ingestion.py"

    # Read current content
    with open(doc_ingestion_path, 'r') as f:
        content = f.read()

    # Check if already updated
    if 'os.getenv' in content and 'QDRANT_MODE' in content:
        print("   ✓ Already configured for environment variables")
        return True

    # Replace connector initialization
    old_code = "self.connector = VectorDBConnector()"
    new_code = """# Support cloud Qdrant via environment variables
        mode = os.getenv("QDRANT_MODE", "local")
        self.connector = VectorDBConnector(
            mode=mode,
            url=os.getenv("QDRANT_URL"),
            api_key=os.getenv("QDRANT_API_KEY")
        )"""

    if old_code in content:
        # Add import if needed
        if "import os" not in content:
            content = "import os\n" + content

        # Replace both occurrences (DocumentIngestionEngine and SelfAwarenessSystem)
        content = content.replace(old_code, new_code)

        # Write back
        with open(doc_ingestion_path, 'w') as f:
            f.write(content)

        print("   ✓ Updated doc_ingestion.py")
        return True
    else:
        print("   ⚠️  Could not find expected code pattern")
        print("   Please update manually:")
        print(f"   File: {doc_ingestion_path}")
        return False


def test_connection():
    """Test connection to cloud Qdrant"""

    print("\n🔍 Testing connection...")

    try:
        sys.path.insert(0, str(Path(__file__).parent.parent))

        from src.core.modules.atomic.vector.connector import VectorDBConnector
        import os

        mode = os.getenv("QDRANT_MODE", "local")
        connector = VectorDBConnector(
            mode=mode,
            url=os.getenv("QDRANT_URL"),
            api_key=os.getenv("QDRANT_API_KEY")
        )

        connector.connect()

        print("   ✅ Connected successfully!")
        print(f"   Mode: {mode}")
        print(f"   URL: {os.getenv('QDRANT_URL', 'local storage')}")

        # List collections
        collections = connector.client.get_collections()
        print(f"   Collections: {len(collections.collections)}")

        connector.disconnect()
        return True

    except Exception as e:
        print(f"   ❌ Connection failed: {str(e)}")
        return False


def main():
    print("\n" + "=" * 60)
    print("  Flyto2 - Cloud Qdrant Setup")
    print("=" * 60)
    print()
    print("This script will help you switch from local Qdrant")
    print("to cloud Qdrant to fix concurrent access issues.")
    print()

    # Step 1: Create .env
    if not create_env_file():
        sys.exit(1)

    # Step 2: Update code
    update_doc_ingestion()

    # Step 3: Test connection
    if test_connection():
        print()
        print("=" * 60)
        print("✅ Setup Complete!")
        print("=" * 60)
        print()
        print("Next steps:")
        print("  1. Re-ingest documents:")
        print("     python scripts/ingest_implementation_guides.py")
        print()
        print("  2. Verify self-awareness:")
        print("     python scripts/verify_self_awareness.py")
        print()
        print("  3. Run tests:")
        print("     python test_end_to_end.py")
        print()
    else:
        print()
        print("=" * 60)
        print("⚠️  Setup incomplete")
        print("=" * 60)
        print()
        print("Please check:")
        print("  - Qdrant server is running")
        print("  - URL and API key are correct")
        print("  - Network connection is available")


if __name__ == "__main__":
    main()
